@dev_host = http://localhost:3000
@id = 5f85447425e9badfde987be8
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmODU0NDc0MjVlOWJhZGZkZTk4N2JlOCIsIm5hbWUiOiLmlrDkuroiLCJpYXQiOjE2MDI2NTQ3MzksImV4cCI6MTYwMzI1OTUzOX0.eytvO1z4NzmFiuVVt-m5nrFR6yRICxgcLbXWSHST1PI

### 注册
POST {{dev_host}}/api/users/register
content-type: application/json

{
    "name": "新人",
    "city": "Beijing",
    "password": "123456"
}

### 登录
POST {{dev_host}}/api/users/login
content-type: application/json

{
    "name": "新人",
    "password": "123456"
}

### 获取userInfo
GET {{dev_host}}/api/users/info
Authorization:Bearer {{token}}

### 获取用户列表
GET {{dev_host}}/api/users

### 获取特定用户
GET {{dev_host}}/api/users/{{id}}?fields=educations;employments;residence

### 修改用户
PATCH {{dev_host}}/api/users/{{id}}
content-type: application/json
Authorization:Bearer {{token}}

{
    "avatar_url": "http://localhost:3000/uploads/upload_54edd1983bf58a6076bf506442ec5e22.png",
    "gender": "male",
    "headline": "我是新人，多多关照",
    "residence": ["北京", "福州", "厦门"],
    "business": "互联网",
    "employments": [
      { "company": "家里蹲", "position": "CEO" }
    ],
    "educations": [
      { "school": "家里蹲大学", "major": "吃土系", "diploma": 4, "entrance_year": 2001, "graduation_year": 2004 }
    ]
}

### 删除用户
DELETE {{dev_host}}/api/users/{{id}}
content-type: application/json
Authorization:Bearer {{token}}

### 关注列表
GET {{dev_host}}/api/users/{{id}}/follow

### 关注某人
PUT {{dev_host}}/api/users/following/{{id}}
content-type: application/json
Authorization:Bearer {{token}}

### 取消关注
DELETE {{dev_host}}/api/users/following/{{id}}
content-type: application/json
Authorization:Bearer {{token}}